b---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
knitr::opts_chunk$set(warnings = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
my_theme <- theme_bw() +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    strip.text = element_text(size = 14),
    panel.grid.minor = element_blank()
  )
theme_set(my_theme)
```


[Olympics Derivations] This problem gives some practice with deriving and visualizing new variables.

```{r}
olympics <- read_csv("https://uwmadison.box.com/shared/static/rzw8h2x6dp5693gdbpgxaf2koqijo12l.csv")
olympics
```

a. Create new columns for the city and country of birth for each athlete in the
London 2012 Olympics
[dataset](https://uwmadison.box.com/s/rzw8h2x6dp5693gdbpgxaf2koqijo12l).

```{r}
olympics |>
  mutate(
    birth_city = str_extract(`Place of birth`, "[A-z]+")
  ) |>
  select(Name, `Place of birth`, birth_city)

olympics <- olympics |>
  mutate(
    birth_city = str_split(`Place of birth`, "\\(")
  ) |>
  unnest_wider(birth_city, "_")
```

b. Compute the standard deviation of athlete age within each sport. Which sport
has widest SD in age? 

```{r}
olympics |>
  select(Name, Sport, Age)

olympics |>
  group_by(Sport) |> # block of rows?
  summarise(sd_age = sd(Age)) |> # aggregation?
  arrange(-sd_age)
```

c. Make a visualization of sports against participant age. Sort sports by
age variance.

```{r}
ggplot(olympics) +
  geom_point(
    aes(Age, reorder(Sport, Age, sd)),
    position = position_jitter(w = 0.2, h = 0.2),
    alpha = 0.4
  )

ggplot(olympics) +
  geom_boxplot(aes(Age, reorder(Sport, Age, sd)))

```